sudo: required
services:
  - docker

before_install:
  - docker build -t knowable/docker-react -f Dockerfile.dev .

script:
  - docker run knowable/docker-react npm run coverage

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-632921519425'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: '$AWS_ACCESS_KEY'
  secret_access_key: '$AWS_SECRET_KEY'
